"""CDP models sit on the platform's declarative base.

The two modules were byte identical before the merge, which is the whole reason
this can be a re-export rather than a reconciliation. Sharing one `Base` means
one metadata, which means one Alembic history: the alternative is two migration
chains pointed at the same database, each unaware of the other's tables, which
goes wrong the first time either is autogenerated.
"""

from sca.models.base import (
    NAMING,
    Base,
    JSONType,
    TimestampMixin,
    UTCDateTime,
    new_id,
)

__all__ = ["NAMING", "Base", "JSONType", "TimestampMixin", "UTCDateTime", "new_id"]
