"""automations

Revision ID: 3862b4ddc933
Revises: 648dc613a950
Create Date: 2026-08-12 15:42:22.608234
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401

# Autogenerate renders custom types by qualified name, so the module has to be
# importable here. It also means the migration carries the JSONB variant and the
# UTC timestamp decorator rather than degrading to plain JSON and naive
# timestamps on Postgres, which is how a hand tidied first migration drifts away
# from the models without anyone noticing.
import sca.models.base  # noqa: F401

revision: str = '3862b4ddc933'
down_revision: str | None = '648dc613a950'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('stop_on_purchase', sa.Boolean(), nullable=False),
    sa.Column('reentry_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automations')),
    sa.UniqueConstraint('name', name='uq_automations_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automations')
    # ### end Alembic commands ###
