"""stock level ledger

Revision ID: 399b3e22da79
Revises: d67032ea0bf7
Create Date: 2026-08-13 11:39:16.371240
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401

# Autogenerate renders custom types by qualified name, so the module has to be
# importable here. It also means the migration carries the JSONB variant and the
# UTC timestamp decorator rather than degrading to plain JSON and naive
# timestamps on Postgres, which is how a hand tidied first migration drifts away
# from the models without anyone noticing.
import sca.models.base  # noqa: F401

revision: str = '399b3e22da79'
down_revision: str | None = 'd67032ea0bf7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_levels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('on_order', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_levels'))
    )
    op.create_index('ix_stock_levels_sku_recorded', 'stock_levels', ['sku', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_levels_sku_recorded', table_name='stock_levels')
    op.drop_table('stock_levels')
    # ### end Alembic commands ###
