"""merge customer data platform into the same schema

Revision ID: 800e9227e7ed
Revises: 6cba230ba358
Create Date: 2026-08-11 21:28:11.195131
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401

# Autogenerate renders custom types by qualified name, so the module has to be
# importable here. It also means the migration carries the JSONB variant and the
# UTC timestamp decorator rather than degrading to plain JSON and naive
# timestamps on Postgres, which is how a hand tidied first migration drifts away
# from the models without anyone noticing.
import sca.models.base  # noqa: F401

revision: str = '800e9227e7ed'
down_revision: str | None = '6cba230ba358'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merged_into_id', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=True),
    sa.Column('preferred_channel', sa.String(length=32), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['persons.id'], name=op.f('fk_persons_merged_into_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons'))
    )
    op.create_index(op.f('ix_persons_merged_into_id'), 'persons', ['merged_into_id'], unique=False)
    op.create_table('raw_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_events')),
    sa.UniqueConstraint('dedupe_key', name='uq_raw_events_dedupe_key')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_consent', sa.String(length=32), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segments')),
    sa.UniqueConstraint('key', name='uq_segments_key')
    )
    op.create_table('activation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('segment_id', sa.String(length=32), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('requested', sa.Integer(), nullable=False),
    sa.Column('delivered', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped_no_consent', sa.Integer(), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_activation_runs_segment_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activation_runs'))
    )
    op.create_table('consent_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('occurred_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_consent_events_person_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_events'))
    )
    op.create_index('ix_consent_person_purpose', 'consent_events', ['person_id', 'purpose', 'occurred_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('raw_event_id', sa.String(length=32), nullable=True),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('value_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_events_person_id')),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], name=op.f('fk_events_raw_event_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_name_occurred', 'events', ['name', 'occurred_at'], unique=False)
    op.create_index('ix_events_person_occurred', 'events', ['person_id', 'occurred_at'], unique=False)
    op.create_table('identifiers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('first_seen_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_identifiers_person_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identifiers')),
    sa.UniqueConstraint('kind', 'value', name='uq_identifiers_kind_value')
    )
    op.create_index('ix_identifiers_person_id', 'identifiers', ['person_id'], unique=False)
    op.create_table('identity_merges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('winner_person_id', sa.String(length=32), nullable=False),
    sa.Column('loser_person_id', sa.String(length=32), nullable=False),
    sa.Column('linked_by_kind', sa.String(length=32), nullable=False),
    sa.Column('linked_by_value', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('reverted_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loser_person_id'], ['persons.id'], name=op.f('fk_identity_merges_loser_person_id')),
    sa.ForeignKeyConstraint(['winner_person_id'], ['persons.id'], name=op.f('fk_identity_merges_winner_person_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_merges'))
    )
    op.create_table('merge_reviews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('person_a_id', sa.String(length=32), nullable=False),
    sa.Column('person_b_id', sa.String(length=32), nullable=False),
    sa.Column('linked_by_kind', sa.String(length=32), nullable=False),
    sa.Column('linked_by_value', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_a_id'], ['persons.id'], name=op.f('fk_merge_reviews_person_a_id')),
    sa.ForeignKeyConstraint(['person_b_id'], ['persons.id'], name=op.f('fk_merge_reviews_person_b_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merge_reviews'))
    )
    op.create_table('person_brand_stats',
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_order_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_brand_stats_person_id')),
    sa.PrimaryKeyConstraint('person_id', 'brand', name=op.f('pk_person_brand_stats'))
    )
    op.create_table('profile_traits',
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('ltv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('aov', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('first_order_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_order_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('recency_days', sa.Integer(), nullable=True),
    sa.Column('rfm', sa.String(length=3), nullable=True),
    sa.Column('brands_purchased', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_profile_traits_person_id')),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_profile_traits'))
    )
    op.create_table('segment_members',
    sa.Column('segment_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('evaluated_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_segment_members_person_id')),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_segment_members_segment_id')),
    sa.PrimaryKeyConstraint('segment_id', 'person_id', name=op.f('pk_segment_members'))
    )
    op.create_table('activation_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('destination', sa.String(length=64), nullable=False),
    sa.Column('consent_basis', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_activation_deliveries_person_id')),
    sa.ForeignKeyConstraint(['run_id'], ['activation_runs.id'], name=op.f('fk_activation_deliveries_run_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activation_deliveries'))
    )
    # The audit log becomes one table for both halves, taking the wider of the two
    # definitions. Batch mode because SQLite cannot ALTER a column in place and the
    # schema parity test runs there: without it the migration is Postgres-only and
    # the test that proves models and migration agree cannot run at all.
    with op.batch_alter_table('audit_log') as batch:
        batch.alter_column('actor',
                   existing_type=sa.VARCHAR(length=64),
                   type_=sa.String(length=128),
                   existing_nullable=False)
        batch.alter_column('entity',
                   existing_type=sa.VARCHAR(length=32),
                   type_=sa.String(length=64),
                   existing_nullable=False)
        # Nullable because the customer side records actions with no subject.
        batch.alter_column('entity_id',
                   existing_type=sa.VARCHAR(length=32),
                   type_=sa.String(length=64),
                   nullable=True)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    with op.batch_alter_table('audit_log') as batch:
        batch.alter_column('entity_id',
                   existing_type=sa.String(length=64),
                   type_=sa.VARCHAR(length=32),
                   nullable=False)
        batch.alter_column('entity',
                   existing_type=sa.String(length=64),
                   type_=sa.VARCHAR(length=32),
                   existing_nullable=False)
        batch.alter_column('actor',
                   existing_type=sa.String(length=128),
                   type_=sa.VARCHAR(length=64),
                   existing_nullable=False)
    op.drop_table('activation_deliveries')
    op.drop_table('segment_members')
    op.drop_table('profile_traits')
    op.drop_table('person_brand_stats')
    op.drop_table('merge_reviews')
    op.drop_table('identity_merges')
    op.drop_index('ix_identifiers_person_id', table_name='identifiers')
    op.drop_table('identifiers')
    op.drop_index('ix_events_person_occurred', table_name='events')
    op.drop_index('ix_events_name_occurred', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_consent_person_purpose', table_name='consent_events')
    op.drop_table('consent_events')
    op.drop_table('activation_runs')
    op.drop_table('segments')
    op.drop_table('raw_events')
    op.drop_index(op.f('ix_persons_merged_into_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
