"""brand compliance

Revision ID: d67032ea0bf7
Revises: a4f7c21b8e93
Create Date: 2026-08-13 09:54:40.733100
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401

# Autogenerate renders custom types by qualified name, so the module has to be
# importable here. It also means the migration carries the JSONB variant and the
# UTC timestamp decorator rather than degrading to plain JSON and naive
# timestamps on Postgres, which is how a hand tidied first migration drifts away
# from the models without anyone noticing.
import sca.models.base  # noqa: F401

revision: str = 'd67032ea0bf7'
down_revision: str | None = 'a4f7c21b8e93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_sites',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('opens_on', sa.Date(), nullable=True),
    sa.Column('closes_on', sa.Date(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_sites')),
    sa.UniqueConstraint('code', name='uq_brand_sites_code')
    )
    op.create_table('brand_standards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('compliance_class', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('site_kind', sa.String(length=16), nullable=True),
    sa.Column('retired_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_standards')),
    sa.UniqueConstraint('code', 'version', name='uq_brand_standards_code_version')
    )
    op.create_index(op.f('ix_brand_standards_code'), 'brand_standards', ['code'], unique=False)
    op.create_table('brand_observations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('captured_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('captured_by', sa.String(length=120), nullable=True),
    sa.Column('campaign', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('quality_reason', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['brand_sites.id'], name=op.f('fk_brand_observations_site_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_observations'))
    )
    op.create_index(op.f('ix_brand_observations_site_id'), 'brand_observations', ['site_id'], unique=False)
    op.create_table('brand_checks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('observation_id', sa.String(length=32), nullable=False),
    sa.Column('standard_id', sa.String(length=32), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('judged_by_kind', sa.String(length=16), nullable=False),
    sa.Column('judged_by', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['brand_observations.id'], name=op.f('fk_brand_checks_observation_id')),
    sa.ForeignKeyConstraint(['standard_id'], ['brand_standards.id'], name=op.f('fk_brand_checks_standard_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_checks')),
    sa.UniqueConstraint('observation_id', 'standard_id', name='uq_brand_checks_observation_standard')
    )
    op.create_index(op.f('ix_brand_checks_observation_id'), 'brand_checks', ['observation_id'], unique=False)
    op.create_index(op.f('ix_brand_checks_standard_id'), 'brand_checks', ['standard_id'], unique=False)
    op.create_table('brand_observation_images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('observation_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('de_identified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['brand_observations.id'], name=op.f('fk_brand_observation_images_observation_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_observation_images')),
    sa.UniqueConstraint('observation_id', 'sha256', name='uq_brand_observation_images_sha')
    )
    op.create_index(op.f('ix_brand_observation_images_observation_id'), 'brand_observation_images', ['observation_id'], unique=False)
    op.create_index(op.f('ix_brand_observation_images_sha256'), 'brand_observation_images', ['sha256'], unique=False)
    op.create_table('brand_findings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('check_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('standard_id', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notified_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=120), nullable=True),
    sa.Column('closed_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['brand_checks.id'], name=op.f('fk_brand_findings_check_id')),
    sa.ForeignKeyConstraint(['site_id'], ['brand_sites.id'], name=op.f('fk_brand_findings_site_id')),
    sa.ForeignKeyConstraint(['standard_id'], ['brand_standards.id'], name=op.f('fk_brand_findings_standard_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_findings'))
    )
    op.create_index(op.f('ix_brand_findings_check_id'), 'brand_findings', ['check_id'], unique=False)
    op.create_index(op.f('ix_brand_findings_site_id'), 'brand_findings', ['site_id'], unique=False)
    op.create_index(op.f('ix_brand_findings_status'), 'brand_findings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_findings_status'), table_name='brand_findings')
    op.drop_index(op.f('ix_brand_findings_site_id'), table_name='brand_findings')
    op.drop_index(op.f('ix_brand_findings_check_id'), table_name='brand_findings')
    op.drop_table('brand_findings')
    op.drop_index(op.f('ix_brand_observation_images_sha256'), table_name='brand_observation_images')
    op.drop_index(op.f('ix_brand_observation_images_observation_id'), table_name='brand_observation_images')
    op.drop_table('brand_observation_images')
    op.drop_index(op.f('ix_brand_checks_standard_id'), table_name='brand_checks')
    op.drop_index(op.f('ix_brand_checks_observation_id'), table_name='brand_checks')
    op.drop_table('brand_checks')
    op.drop_index(op.f('ix_brand_observations_site_id'), table_name='brand_observations')
    op.drop_table('brand_observations')
    op.drop_index(op.f('ix_brand_standards_code'), table_name='brand_standards')
    op.drop_table('brand_standards')
    op.drop_table('brand_sites')
    # ### end Alembic commands ###
