"""initial schema

Revision ID: e9c9a63e291f
Revises: 
Create Date: 2026-08-10 23:51:30.093684
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql  # noqa: F401

# Autogenerate renders custom types by qualified name, so the module has to be
# importable here. It also means the migration carries the JSONB variant and the
# UTC timestamp decorator rather than degrading to plain JSON and naive
# timestamps on Postgres, which is how a hand tidied first migration drifts away
# from the models without anyone noticing.
import sca.models.base  # noqa: F401

revision: str = 'e9c9a63e291f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('inbound_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('supplier_id', sa.String(length=32), nullable=True),
    sa.Column('purchase_order_id', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.String(length=20000), nullable=False),
    sa.Column('received_at', sca.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('processed_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_messages')),
    sa.UniqueConstraint('external_id', name='uq_inbound_messages_external_id')
    )
    op.create_index(op.f('ix_inbound_messages_purchase_order_id'), 'inbound_messages', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_inbound_messages_supplier_id'), 'inbound_messages', ['supplier_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('moq', sa.Integer(), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('sku', name=op.f('uq_items_sku'))
    )
    op.create_table('stock_snapshots',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('on_order', sa.Integer(), nullable=False),
    sa.Column('weekly_forecast', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sku', name=op.f('pk_stock_snapshots'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('working_days', sa.String(length=20), nullable=False),
    sa.Column('work_start_hour', sa.Integer(), nullable=False),
    sa.Column('work_end_hour', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('min_order_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('code', name=op.f('uq_suppliers_code'))
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_reason', sa.String(length=200), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scheduled_send_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('reminded_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery_date', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('confirmed_delivery_date', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('number', name=op.f('uq_purchase_orders_number'))
    )
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('source_message_id', sa.String(length=32), nullable=True),
    sa.Column('extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_documents_purchase_order_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_purchase_order_id'), 'documents', ['purchase_order_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=32), nullable=True),
    sa.Column('supplier_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('suggested_action', sa.String(length=500), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=500), nullable=True),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_issues_purchase_order_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    op.create_index(op.f('ix_issues_purchase_order_id'), 'issues', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_issues_supplier_id'), 'issues', ['supplier_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_lines_purchase_order_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines'))
    )
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=32), nullable=False),
    sa.Column('carrier', sa.String(length=32), nullable=False),
    sa.Column('tracking_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('eta', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sca.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sca.models.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_shipments_purchase_order_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments'))
    )
    op.create_index(op.f('ix_shipments_purchase_order_id'), 'shipments', ['purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_purchase_order_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_issues_supplier_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_purchase_order_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_documents_purchase_order_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('suppliers')
    op.drop_table('stock_snapshots')
    op.drop_table('items')
    op.drop_index(op.f('ix_inbound_messages_supplier_id'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_purchase_order_id'), table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
