import uuid
from datetime import UTC, datetime

from sqlalchemy import JSON, DateTime, MetaData, TypeDecorator, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Named constraint conventions so autogenerated migrations produce stable names
# instead of whatever the backend invents.
NAMING = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING)


# JSONB on Postgres (indexable, typed) and plain JSON on SQLite so the suite can
# run without a container. The application never depends on JSONB operators;
# anything that would need them belongs in a real column instead.
JSONType = JSON().with_variant(JSONB(), "postgresql")


class UTCDateTime(TypeDecorator):
    """Every timestamp is stored in UTC and read back timezone-aware.

    Without this the application is silently backend-dependent: Postgres returns
    aware datetimes, SQLite returns naive ones, and comparing the two raises at
    runtime. Normalising at the type boundary means no service ever has to guess
    which it is holding — the DB stores UTC, the business timezone (Asia/Riyadh)
    is a presentation concern only.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect) -> datetime | None:
        if value is None:
            return None
        # A naive datetime reaching the DB is a bug upstream; treating it as UTC
        # is the least surprising interpretation and keeps it comparable.
        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect) -> datetime | None:
        if value is None:
            return None
        return value if value.tzinfo is not None else value.replace(tzinfo=UTC)


def new_id() -> str:
    return uuid.uuid4().hex


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        UTCDateTime, server_default=func.now(), nullable=False
    )
